apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plane-tracker

resources:
- ../../base

# CI updates the tag here via `kustomize edit set image`.
images:
- name: plane-tracker
  newName: docker.io/makeplane/plane-tracker
  newTag: 12b6adb3ff3001b2ccb418bdce50a25971550f91
