apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plane-tracker

resources:
- ../../base

# CI updates the tag here via `kustomize edit set image`.
images:
- name: plane-tracker
  newName: docker.io/makeplane/plane-tracker
  newTag: e489791788cb578734dd5e297de6a451471f272e
